export const Routes = {
  HOME: '/',
  TERMS_AND_CONDITIONS: '/terms-and-conditions',
  SIGN_UP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  APPOINTMENTS: '/appointments',
  APPOINTMENT_CREATE: '/appointment',
  APPOINTMENT_UPDATE: '/appointment/:slug',
  ADMIN: '/admin',
  ACCOUNT: '/account',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  HELP: '/help',
  LOGOUT: '/logout',
}
