/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./public/index.html', './pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    fontFamily: {
      sans: ['Poppins', 'sans-serif'],
      serif: ['Bitter', 'serif'],
    },
    colors: {
      transparent: 'transparent',
      black: '#000000DE',
      white: '#FFFFFFDE',
      backdrop: '#292929BF',
      highlight: '#FF7A45DE',
      'light-mode': {
        DEFAULT: '#2673DD',
        secondary: '#2673DDBF',
        tertiary: '#F4F8FD',
        border: '#C7D0DE',
        background: { DEFAULT: '#F1F5F9', secondary: '#E2E8F0', tertiary: '#E8E8E8' },
        foreground: { DEFAULT: '#FFFFFF' },
        text: { DEFAULT: '#000000DE', secondary: '#00000099', tertiary: '#00000061' },
        link: { DEFAULT: '#639BF6', target: '#486082' },
        success: { DEFAULT: '#44CC77', background: '#44CC774D' },
        warning: { DEFAULT: '#FFBB00', background: '#FFBB004D' },
        error: { DEFAULT: '#EE2C4A', background: '#EE2C4A33' },
      },
      'dark-mode': {
        DEFAULT: '#2673DD',
        secondary: '#2673DDB3',
        tertiary: '#15202E',
        border: '#E8E8E817',
        background: { DEFAULT: '#1B1C22', secondary: '#1B1C22E6', tertiary: '#22252A' },
        foreground: { DEFAULT: '#151515' },
        text: { DEFAULT: '#FFFFFFDE', secondary: '#FFFFFF99', tertiary: '#FFFFFF61' },
        link: { DEFAULT: '#639BF6', target: '#486082' },
        success: { DEFAULT: '#309053', background: '#3090534D' },
        warning: { DEFAULT: '#B2B400', background: '#B2B4004D' },
        error: { DEFAULT: '#A82B30', background: '#A82B304D' },
      },
    },
    screens: {
      sm: '480px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    extend: {
      gridTemplateAreas: {
        'layout-unauth': ['header', 'main', 'footer'],
        'layout-unauth-lg': ['sidebar main', 'footer footer'],
        'layout-auth': ['header', 'main', 'footer'],
        'layout-auth-lg': ['header', 'main', 'footer'],
      },
      gridTemplateRows: {
        'layout-unauth': '125px auto max-content',
        'layout-unauth-lg': 'auto max-content',
        'layout-auth': '125px auto max-content',
        'layout-auth-lg': 'max-content auto max-content',
        nav: 'auto max-content',
        main: 'auto min-content',
        'dialog-panel-sm': 'max-content auto max-content',
      },
      gridTemplateColumns: {
        'layout-unauth': '100%',
        'layout-auth': '100%',
        'layout-unauth-lg': '50%',
        'layout-auth-lg': '100%',
        'nav-lg': 'auto max-content',
        listbox: '16px max-content',
        'radio-group': '1fr 16px',
        tab: 'repeat(auto-fit, minmax(50px, 1fr))',
      },
      width: {
        'max-content': 'max-content',
      },
      minHeight: {
        'nav-expanded': 'calc(100vh - 125px)',
      },
      backgroundImage: {
        landing: 'linear-gradient(to top, #2673DDBA, #FFFFFFBF), url(/assets/images/backgrounds/landing.jpg)',
        'landing-dark': 'linear-gradient(to top, #2673DDBA, #000000BF), url(/assets/images/backgrounds/landing.jpg)',
        dropdown: 'url(/assets/images/icons/chevron-down.svg)',
        calendar: 'url(/assets/images/icons/calendar-regular.svg)',
      },
      backgroundPosition: {
        dropdown: 'calc(100% - 12px) center',
      },
      backgroundSize: {
        dropdown: '16px',
      },
      fontSize: {
        sm: '0.8rem',
        base: '1rem',
        xl: '1.25rem',
        '2xl': '1.563rem',
        '3xl': '1.953rem',
        '4xl': '2.441rem',
        '5xl': '3.052rem',
      },
      aria: {
        none: 'sort="none"',
        asc: 'sort="ascending"',
        desc: 'sort="descending"',
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  plugins: [require('@headlessui/tailwindcss')({ prefix: 'ui' }), require('@savvywombat/tailwindcss-grid-areas')],
}
